apiVersion: v1
kind: Secret
metadata:
  name: peakload-api-secret
  namespace: peakload
type: Opaque
stringData:
  POSTGRES_DB: "peakload_db"
  POSTGRES_USER: "peakload_user"
  POSTGRES_PASSWORD: "CHANGEME"
  DATABASE_SHARD0_WRITE_URL: "postgres://peakload_user:CHANGEME@host.docker.internal:5000/peakload_db"
  DATABASE_SHARD1_WRITE_URL: "postgres://peakload_user:CHANGEME@host.docker.internal:5001/peakload_db"
  DATABASE_SHARD0_READ_URLS: "postgres://peakload_user:CHANGEME@host.docker.internal:5000/peakload_db"
  DATABASE_SHARD1_READ_URLS: "postgres://peakload_user:CHANGEME@host.docker.internal:5001/peakload_db"
  REDIS_URL: "redis://:CHANGEME@host.docker.internal:6379"
  REDIS_READ_URL: "redis://:CHANGEME@host.docker.internal:6380"
  REDIS_SENTINEL_NODES: "redis://host.docker.internal:26379,redis://host.docker.internal:26380,redis://host.docker.internal:26381"
  RABBITMQ_URL: "amqp://peakload_user:CHANGEME@host.docker.internal:5672"
